# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['leta_app.py'],
    pathex=[],
    binaries=[],
    datas=[('KULLANIM_KILAVUZU.txt', '.')],
    hiddenimports=[
        'ttkbootstrap',
        'ttkbootstrap.constants',
        'ttkbootstrap.themes',
        'ttkbootstrap.style',
        'ttkbootstrap.widgets',
        'ttkbootstrap.dialogs',
        'ttkbootstrap.tooltip',
        'ttkbootstrap.scrolled',
        'pandas',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'openpyxl',
        'sqlite3',
        'datetime',
        'hashlib',
        'json',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'torch', 
        'tensorflow', 
        'scipy', 
        'sklearn', 
        'matplotlib', 
        'cv2', 
        'transformers', 
        'spacy', 
        'cryptography', 
        'grpc', 
        'h5py', 
        'lxml', 
        'sympy',
        'jinja2',
        'pytest',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Leta_Pipeline_v1_3',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

